# The URL the site will be built for
base_url = "https://vtta.github.io"
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# Used in RSS by default
title = "vtta"
description = "vtta's homepage"
# The default language, used in RSS
default_language = "en"
# Theme name to use
# theme = "even"
theme = "hermit"
# Which theme to use for the code highlighting.
# See below for list of accepted values
# https://www.getzola.org/documentation/getting-started/configuration/
#highlight_theme = "ayu-light"
highlight_theme = "agola-dark"
# Whether to generate a RSS feed automatically
generate_rss = true
# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20
# Whether to copy or hardlink files in static/ directory. Useful for sites
# whose static files are large. Note that for this to work, both static/ and
# output directory need to be on the same filesystem. Also, theme's static/
# files are always copies, regardles of this setting. False by default.
# hard_link_static = false
# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "tags", lang = "fr"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
    # You can enable/disable RSS
    { name = "tags", rss = true },
]
# The additional languages for that site
# Example:
#     languages = [
#       {code = "fr", rss = true}, # there will be a RSS feed for French content
#       {code = "fr", search = true}, # there will be a Search Index for French content
#       {code = "it"}, # there won't be a RSS feed for Italian content
#     ]
#
languages = []
# Whether to compile the Sass files found in the `sass` directory
compile_sass = true
# Whether to build a search index out of the pages and section to be used later on by a JavaScript library
# content for the `default_language`
build_search_index = true
# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []
# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

# Optional translation object. The key if present should be a language code.
# Example:
#     default_language = "fr"
#
#     [translations]
#     [translations.fr]
#     title = "Un titre"
#
#     [translations.en]
#     title = "A title"
#
[translations]

# You can put any kind of data in there and it
# will be accessible in all templates
## [extra]
## Put all your custom variables here
## even theme
## katex_enable = true
## katex_auto_render = true
## even_title = "vtta"
## # This is the default menu
## even_menu = [
##     { url = "$BASE_URL", name = "Home" },
##     { url = "$BASE_URL/categories", name = "Categories" },
##     { url = "$BASE_URL/tags", name = "Tags" },
##     { url = "$BASE_URL/about", name = "About" },
## ]
[extra]
home_subtitle = "vtta's homepage"
footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/tags", name = "Tags" },
    { link = "/about", name = "About" }
]
hermit_social = [
    { name = "github", link = "https://github.com/vtta" },
    { name = "instagram", link = "https://www.instagram.com/vtta0124/" },
    { name = "email", link = "mailto:vtta0124@gmail.com" }
]

# Add custom css
# customCSS = ["css/foo.css", "css/bar.css"]
[extra.author]
name = "vtta"
email = "vtta0124@gmail.com"

[extra.google_analytics]
enable = true
id = "UA-156442381-1"
